export enum FlowState {
  // Entry point
  WELCOME = 'WELCOME',
  WAITING_MAIN_MENU = 'WAITING_MAIN_MENU',

  // Immediate medical attention
  IMMEDIATE_ATTENTION_ASK_LOCATION = 'IMMEDIATE_ATTENTION_ASK_LOCATION',
  IMMEDIATE_ATTENTION_CONFIRM = 'IMMEDIATE_ATTENTION_CONFIRM',

  // Telemedicine
  TELEMEDICINE_ASK_ID = 'TELEMEDICINE_ASK_ID',
  TELEMEDICINE_VALIDATE = 'TELEMEDICINE_VALIDATE',

  // Home care
  HOME_CARE_ASK_CITY = 'HOME_CARE_ASK_CITY',
  HOME_CARE_SHOW_INFO = 'HOME_CARE_SHOW_INFO',
  HOME_CARE_CONFIRM = 'HOME_CARE_CONFIRM',

  // Medical consultations
  CONSULTATION_ASK_SPECIALTY = 'CONSULTATION_ASK_SPECIALTY',
  CONSULTATION_SHOW_INFO = 'CONSULTATION_SHOW_INFO',
  CONSULTATION_CONFIRM = 'CONSULTATION_CONFIRM',

  // Laboratory
  LAB_ASK_TESTS = 'LAB_ASK_TESTS',
  LAB_SHOW_INFO = 'LAB_SHOW_INFO',
  LAB_CONFIRM = 'LAB_CONFIRM',

  // Ambulance
  AMBULANCE_ASK_CITY = 'AMBULANCE_ASK_CITY',
  AMBULANCE_SHOW_INFO = 'AMBULANCE_SHOW_INFO',
  AMBULANCE_CONFIRM = 'AMBULANCE_CONFIRM',

  // Pharmacy
  PHARMACY_REDIRECT = 'PHARMACY_REDIRECT',

  // Equipment rental
  EQUIPMENT_ASK_ITEM = 'EQUIPMENT_ASK_ITEM',
  EQUIPMENT_SHOW_INFO = 'EQUIPMENT_SHOW_INFO',
  EQUIPMENT_CONFIRM = 'EQUIPMENT_CONFIRM',

  // Plans
  PLANS_SHOW = 'PLANS_SHOW',
  PLANS_DETAIL = 'PLANS_DETAIL',
  PLANS_CONNECT_AGENT = 'PLANS_CONNECT_AGENT',

  // Final
  END = 'END',
}
