export default () => ({
  TWILIO_ACCOUNT_SID: String(process.env.TWILIO_ACCOUNT_SID),
  TWILIO_AUTH_TOKEN: String(process.env.TWILIO_AUTH_TOKEN),
  TWILIO_PHONE_NUMBER: String(process.env.TWILIO_PHONE_NUMBER),
  WHATSAPP_VERIFY_TOKEN: String(process.env.WHATSAPP_VERIFY_TOKEN),
  WHATSAPP_IDENTIFIER: String(process.env.WHATSAPP_IDENTIFIER),
  META_ACCESS_TOKEN: String(process.env.META_ACCESS_TOKEN),
  META_PHONE_NUMBER_ID: String(process.env.META_PHONE_NUMBER_ID),
  DB_HOST: String(process.env.DB_HOST),
  DB_PORT: Number(process.env.DB_PORT),
  DB_USERNAME: String(process.env.DB_USERNAME),
  DB_PASSWORD: String(process.env.DB_PASSWORD),
  DB_NAME: String(process.env.DB_NAME),
  REDIS_URL: String(process.env.REDIS_URL),
});
