import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigration1761684000204 implements MigrationInterface {
    name = 'InitialMigration1761684000204'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."users_roles_enum" AS ENUM('super_admin', 'clinic_admin', 'operator', 'doctor', 'nurse', 'receptionist', 'lab_admin', 'finance')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "first_name" character varying(100) NOT NULL, "last_name" character varying(100) NOT NULL, "phone" character varying(20), "email" character varying(100) NOT NULL, "password_hash" character varying(255) NOT NULL, "roles" "public"."users_roles_enum" array NOT NULL DEFAULT '{clinic_admin}', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "last_login" TIMESTAMP, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "specialties" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "description" text, "status" character varying(50) NOT NULL DEFAULT 'Active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP, CONSTRAINT "UQ_565f38f8b0417c7dbd40e429782" UNIQUE ("name"), CONSTRAINT "PK_ba01cec5aa8ac48778a1d097e98" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "doctors" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "first_name" character varying(100) NOT NULL, "last_name" character varying(100) NOT NULL, "license_number" character varying(50) NOT NULL, "phone" character varying(20), "qualifications" text, "years_of_experience" integer, "status" character varying(50) NOT NULL DEFAULT 'Active', "office_address" character varying(255), "consultation_hours_start" TIME, "consultation_hours_end" TIME, "consultation_fee" numeric(10,2), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP, "specialty_id" uuid, CONSTRAINT "UQ_16d3ee4c62bb957e17d70412632" UNIQUE ("license_number"), CONSTRAINT "PK_8207e7889b50ee3695c2b8154ff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "clinical_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "appointment_date" TIMESTAMP NOT NULL DEFAULT now(), "reason_for_visit" text NOT NULL, "diagnosis" text NOT NULL, "treatment" text, "observations" text, "appointment_type" character varying(100), "weight_kg" numeric(5,2), "height_cm" numeric(5,2), "blood_pressure" character varying(20), "temperature_celsius" numeric(5,2), "heart_rate_bpm" integer, "prescribed_medications" text, "lab_results" text, "follow_up_date" date, "appointment_status" character varying(50) NOT NULL DEFAULT 'Completed', "consultation_fee" numeric(10,2), "additional_notes" text, "patient_id" uuid, "doctor_id" uuid, CONSTRAINT "PK_88bb9264ee0dcf6cea9c92d07d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "private_plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "category" character varying(100) NOT NULL, "max_beneficiaries" integer NOT NULL DEFAULT '1', "family_discount" numeric(10,2), "includes_preventive_care" boolean NOT NULL DEFAULT false, "includes_dental" boolean NOT NULL DEFAULT false, "includes_vision" boolean NOT NULL DEFAULT false, "plan_id" uuid, CONSTRAINT "REL_ca37ab2e7be390a77a37a9e54d" UNIQUE ("plan_id"), CONSTRAINT "PK_d73ed2aad3fedcbb0008e19493a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "corporate_plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "company_name" character varying(200) NOT NULL, "company_tax_id" character varying(20) NOT NULL, "company_contact" character varying(150), "company_address" character varying(255), "company_email" character varying(100), "company_phone" character varying(20), "number_of_employees" integer, "employee_contribution_percentage" numeric(10,2), "plan_id" uuid, CONSTRAINT "UQ_36d0c08dcf0a18f9831c2dcaa1a" UNIQUE ("company_tax_id"), CONSTRAINT "REL_afcfe52dbf8607643909390329" UNIQUE ("plan_id"), CONSTRAINT "PK_a01a51230ade7d7d6abbd858380" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."plans_plan_type_enum" AS ENUM('Private', 'Corporate')`);
        await queryRunner.query(`CREATE TABLE "plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "plan_name" character varying(150) NOT NULL, "description" text, "plan_type" "public"."plans_plan_type_enum" NOT NULL, "monthly_cost" numeric(10,2) NOT NULL DEFAULT '0', "status" character varying(50) NOT NULL DEFAULT 'Active', "coverage_period_months" integer NOT NULL DEFAULT '1', "deductible" numeric(10,2), "copayment" numeric(10,2), "coinsurance" numeric(10,2), "max_annual_coverage" integer, "coverage_details" text, "exclusions" text, "effective_date" date, "expiration_date" date, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP, CONSTRAINT "UQ_0b3866daf36d0d6520c9d1f5ef3" UNIQUE ("plan_name"), CONSTRAINT "PK_3720521a81c7c24fe9b7202ba61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "start_date" date NOT NULL, "end_date" date, "subscription_status" character varying(50) NOT NULL DEFAULT 'Active', "total_cost" numeric(10,2), "payment_method" character varying(50), "payment_reference" character varying(100), "last_payment_date" date, "next_payment_date" date, "auto_renewal" boolean NOT NULL DEFAULT false, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP, "patient_id" uuid, "plan_id" uuid, "holder_subscription_id" uuid, CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "patients" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "first_name" character varying(100) NOT NULL, "last_name" character varying(100) NOT NULL, "birth_date" date, "gender" character varying(50) NOT NULL, "document_type" character varying(50) NOT NULL, "document_number" character varying(50) NOT NULL, "address" character varying(255), "city" character varying(100), "state" character varying(100), "zip_code" character varying(20), "phone" character varying(20), "secondary_phone" character varying(20), "emergency_contact_name" character varying(255), "emergency_contact_phone" character varying(20), "blood_type" character varying(50), "allergies" text, "medical_conditions" text, "patient_status" character varying(50) NOT NULL DEFAULT 'Active', "medical_record_number" character varying(50), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP, CONSTRAINT "UQ_85bcb7ae36549e3eb85686078d0" UNIQUE ("document_number"), CONSTRAINT "PK_a7f0b9fcbb3469d5ec0b0aceaa7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tickets_servicetype_enum" AS ENUM('immediate_attention', 'telemedicine', 'home_care', 'medical_consultation', 'ambulance', 'laboratory', 'appointment')`);
        await queryRunner.query(`CREATE TYPE "public"."tickets_status_enum" AS ENUM('pending', 'assigned', 'in_progress', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."tickets_priority_enum" AS ENUM('low', 'medium', 'high', 'urgent')`);
        await queryRunner.query(`CREATE TABLE "tickets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "referenceNumber" SERIAL NOT NULL, "serviceType" "public"."tickets_servicetype_enum" NOT NULL, "status" "public"."tickets_status_enum" NOT NULL DEFAULT 'pending', "priority" "public"."tickets_priority_enum" NOT NULL DEFAULT 'medium', "patientId" uuid, "requesterPhone" character varying NOT NULL, "requesterName" text, "location" text, "municipality" text, "speciality" text, "description" text, "assignedTo" character varying, "assignedAt" TIMESTAMP, "completedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8caf8d7250f1338ba6f283d3c0e" UNIQUE ("referenceNumber"), CONSTRAINT "PK_343bc942ae261cf7a1377f48fd0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD CONSTRAINT "FK_67d7cd9e927b1dca13d42511c02" FOREIGN KEY ("specialty_id") REFERENCES "specialties"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clinical_records" ADD CONSTRAINT "FK_eb74d4b2b8f0df15f578a5634c5" FOREIGN KEY ("patient_id") REFERENCES "patients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clinical_records" ADD CONSTRAINT "FK_939df53adf4733e5286ca42eb9e" FOREIGN KEY ("doctor_id") REFERENCES "doctors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "private_plans" ADD CONSTRAINT "FK_ca37ab2e7be390a77a37a9e54db" FOREIGN KEY ("plan_id") REFERENCES "plans"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "corporate_plans" ADD CONSTRAINT "FK_afcfe52dbf8607643909390329d" FOREIGN KEY ("plan_id") REFERENCES "plans"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_89aed9732ffe67192b4c4fd72d3" FOREIGN KEY ("patient_id") REFERENCES "patients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_e45fca5d912c3a2fab512ac25dc" FOREIGN KEY ("plan_id") REFERENCES "plans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_90d281a4ee91f5a16f025bc64c4" FOREIGN KEY ("holder_subscription_id") REFERENCES "subscriptions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_7c2894ec48d1aeeb9a57680ab12" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_7c2894ec48d1aeeb9a57680ab12"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_90d281a4ee91f5a16f025bc64c4"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_e45fca5d912c3a2fab512ac25dc"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_89aed9732ffe67192b4c4fd72d3"`);
        await queryRunner.query(`ALTER TABLE "corporate_plans" DROP CONSTRAINT "FK_afcfe52dbf8607643909390329d"`);
        await queryRunner.query(`ALTER TABLE "private_plans" DROP CONSTRAINT "FK_ca37ab2e7be390a77a37a9e54db"`);
        await queryRunner.query(`ALTER TABLE "clinical_records" DROP CONSTRAINT "FK_939df53adf4733e5286ca42eb9e"`);
        await queryRunner.query(`ALTER TABLE "clinical_records" DROP CONSTRAINT "FK_eb74d4b2b8f0df15f578a5634c5"`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP CONSTRAINT "FK_67d7cd9e927b1dca13d42511c02"`);
        await queryRunner.query(`DROP TABLE "tickets"`);
        await queryRunner.query(`DROP TYPE "public"."tickets_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tickets_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tickets_servicetype_enum"`);
        await queryRunner.query(`DROP TABLE "patients"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TABLE "plans"`);
        await queryRunner.query(`DROP TYPE "public"."plans_plan_type_enum"`);
        await queryRunner.query(`DROP TABLE "corporate_plans"`);
        await queryRunner.query(`DROP TABLE "private_plans"`);
        await queryRunner.query(`DROP TABLE "clinical_records"`);
        await queryRunner.query(`DROP TABLE "doctors"`);
        await queryRunner.query(`DROP TABLE "specialties"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_roles_enum"`);
    }

}
